name: CI/CD Pipeline for Calculator App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Node.js for linting JavaScript
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    # Install dependencies (eslint for linting)
    - name: Install dependencies
      run: npm install eslint --save-dev

    # Run ESLint to check JavaScript code
    - name: Run linting
      run: npx eslint index.html --ext .js

    # Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./