name: "CI/CD pipeline for the Calculator App"

on:
  push:
    branches:
    - main

jobs:
  build=and-deploy:
    runs-on: ubuntu-latest

    steps:
    #checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v4
    - name: setup Node js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: install dependencies
      run: npm install eslint --save-dev
    # Deploy to Github Pages
    - name: Deploy to Github Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        publish_dir: ./